pool:
  name: Hosted Windows 2019 with VS2019

variables:
- group: iot-module-pump-group

steps:
- task: AzureIoTEdge@2
  displayName: 'Azure IoT Edge - Build module images'
  inputs:
    deploymentid: 'azuredevops-deployment'
    templateFilePath: deployment.template.json
    defaultPlatform: 'windows-amd64'

- task: AzureIoTEdge@2
  displayName: 'Azure IoT Edge - Push Module Images'
  inputs:
    action: 'Push module images'
    containerregistrytype: Azure Container Registry
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureContainerRegistry: $(azureContainerRegistry)
    templateFilePath: deployment.template.json
    defaultPlatform: windows-amd64 

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'

