pool:
  name: Hosted Windows 2019 with VS2019

variables:
- group: iot-module-pump-group

steps:
- task: CopyFiles@2
  displayName: 'Copy unaltered source to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: 
    Contents: '/**/*.*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    
- task: AzureIoTEdge@2
  displayName: 'Azure IoT Edge - Build module images'
  inputs:
    defaultPlatform: 'windows-amd64'

- task: AzureIoTEdge@2
  displayName: 'Azure IoT Edge - Push Module Images'
  inputs:
    action: 'Push module images'
    containerregistrytype: Azure Container Registry
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureContainerRegistry: $(azureContainerRegistry)
    defaultPlatform: windows-amd64 

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'

