# Required Variables
# ACR_HOST:  myregistry.azurecr.io
# ACR_USER:  registryUser
# ACR_PASSWORD: registryPassword
# ACR_REGISTRY: {"loginServer":"{registryName}.azurecr.io", "id" : "/subscriptions/{azureSubscription}/resourceGroups/{resourceGroupName/providers/Microsoft.ContainerRegistry/registries/{registryName"}
# SERVICE_ENDPOINT: myService


pool:
  name: Hosted Windows 2019 with VS2019

variables:
- group: iot-module-pump-group

steps:

- task: qetza.replacetokens.replacetokens-task.replacetokens@3
  displayName: 'Replace tokens in modules/**/module.json'
  inputs:
    rootDirectory: 
    targetFiles: 'modules/**/module.json'
   
- task: AzureIoTEdge@2
  displayName: 'Azure IoT Edge - Build module images'
  inputs:
    defaultPlatform: 'windows-amd64'

- task: AzureIoTEdge@2
  displayName: 'Azure IoT Edge - Push Module Images'
  inputs:
    action: 'Push module images'
    containerregistrytype: Azure Container Registry
    azureSubscriptionEndpoint: $(SERVICE_ENDPOINT)
    azureContainerRegistry: $(ACR_REGISTRY)
    defaultPlatform: windows-amd64 
    
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'

