    
version: v1.0.0
steps:
  - build: -t {{.Run.Registry}}/module-pump-win:{{.Run.ID}} -t {{.Run.Registry}}/module-pump-win:1.5 -f ./modules/PumpModule/Dockerfile.windows-amd64 ./modules/PumpModule
    timeout: 2000
  - push:
    - {{.Run.Registry}}/module-pump-win:{{.Run.ID}}
    - {{.Run.Registry}}/module-pump-win:1.5