version: 1.0-preview-1
steps:
  - build: -t {{.Run.Registry}}/simulated-win-sensor:{{.Run.ID}} -t {{.Run.Registry}}/simulated-win-sensor:latest -f Dockerfile .
  - push:
    - {{.Run.Registry}}/simulated-win-sensor:{{.Run.ID}}
    - {{.Run.Registry}}/simulated-win-sensor:latest